### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by asobolev**
Here are a few changes needed to make nixpy work with python3.

One major change - we cannot use metaprogramming to inject methods as elegant as before (see "The Metaclass Hook in Python 3" here http://python-3-patterns-idioms-test.readthedocs.org/en/latest/Metaprogramming.html). So I used the easy solution and monkey patch classes directly (could be easily changed later if you'd like).

All tests run fine EXCEPT 2 TESTS in data set. Something is wrong with indexing ("selection+offset not within extent"). It would be nice if someone who developed DataSet could take a look and fix these.

Other than that it should be fine.

### CODE REVIEW

**Comment by stoewer** [comment]
> could be easily changed later if you'd like

If it is so easy I would prefer to change it right now

**Comment by asobolev** [comment]
I don't have time at the moment to investigate what is the best solution for patching. If you could propose something better than direct patching - I could try to integrate it later (or of course one could always fetch my branch and just do that).

**Comment by gicmo** [comment]
Something strange is going on with coveralls. According to travis coverage is:
```
TOTAL                       1840     36    98%   
```

**Comment by jgrewe** [comment]
Well, this looks better ;)
I have a problem though. The code compiles with python 3.4 but tests are not running on my machine due to some import error  

from nix.core import File, FileMode, Block, DataType, Section, Property, Value, \
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0: undefined symbol: PyClass_Type

do you have some advice for me?  My system linux mint/ubuntu libboost-python 1.54, used python3.4

**Comment by gicmo** [comment]
@jgrewe that happens when you at runtime you use python3 but it was linked against boost-python for python 2. Maybe the new boost python selection code didn't work correctly or something else went wrong

**Comment by asobolev** [comment]
Jan, could you please send the results of the following with your python3.4:

import platform
platform.system()

as well as

locate libboost_python

Thanks

**Comment by jgrewe** [comment]
sure:

platform.system() just gives 'linux'

Actually it is a linux mint 17, 64 bit 

locate libboost_python:
/usr/lib/x86_64-linux-gnu/libboost_python-py27.a
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_python-py34.a
/usr/lib/x86_64-linux-gnu/libboost_python-py34.so
/usr/lib/x86_64-linux-gnu/libboost_python-py34.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_python.a
/usr/lib/x86_64-linux-gnu/libboost_python.so

**Comment by gicmo** [comment]
@jgrewe you have the latests commits? Can you make sure it tries and does indeed link against `libboost_python-py34` during `python setup.py build`

**Comment by asobolev** [comment]
How do you build it? 

usually just doing "python3 setup.py build" raises a numpy error (no numpy for python3 by default). So I usually do it with virtualenv, and you?

**Comment by jgrewe** [comment]
sorry was out of the office for a while...
Actually I was behind by a few commits. 
Just trying to build again with: 
sudo python3.4 setup.py build

**Comment by jgrewe** [comment]
build passes with a tiny warning:
In static member function ‘static void* nixpy::PyDataSet::do_export()’:
src/PyDataSet.cpp:285:1: warning: control reaches end of non-void function [-Wreturn-type]
 }

tests are running, installation and import are working now

**Pull request merged**
