### PR TITLE
File ID, header creation modifications, and File Format 1.2.0

### PR DESCRIPTION
**Pull request by achilleas-k**
Added ID in the file header.  Attribute key `id`.

Removed header property setters.  See corresponding commit for full explanation.

Updated file format version to 1.2.0.

### CODE REVIEW

**Comment by achilleas-k** [comment]
New commits: Tests and validator

**Comment by achilleas-k** [comment]
Can I get a review/merge on this (once tests are done)?  I'll rebase and fixup #452 after (which includes these commits, but needs a bit more work).

**Comment by jgrewe** [comment]
@achilleas-k as I read your comment on #452, I assumed you wanted to merge them in one go, sorry

**Comment by achilleas-k** [comment]
Merged via #452

**Pull request closed without merging**
