### PR TITLE
[pprint] max_depth=-1 is now default

### PR DESCRIPTION
**Pull request by jgrewe**

### CODE REVIEW

**Review by mpsonntag — DISMISSED** [review]
LGTM

**Review by achilleas-k — DISMISSED** [review]

**Comment by achilleas-k** [comment]
Needs a rebase.

**Comment by jgrewe** [comment]
@achilleas-k  thanks for pinging... Will do but I also need to (re)consider the side effect of this choice on the nixio command line tool, which will then print out the whole metadata tree.
Is that a bad choice? I am not sure. If yes, then I will limit the default recursion depth there. 
What do you think?

**Comment by achilleas-k** [comment]
I  think it's fine to spew everything out by default.  It might be a bit annoying, but no more than any other command line tool that produces multiple pages of output by default.

**Comment by jgrewe** [comment]
@achilleas-k  rebased ;)

**Review by gicmo — APPROVED** [review]
LGTM
(naughty whitespace changes ;)

**Pull request merged**
